Make auto poetry install run only once

diff --git a/scripts/hooks/post-merge b/scripts/hooks/post-merge
--- a/scripts/hooks/post-merge
+++ b/scripts/hooks/post-merge
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
 
-while true; do
-    poetry install --sync --with=docs
-    exit_status=$?
+poetry install
+exit_status=$?
 
-    if [[ $exit_status -eq 0 ]]; then
-        echo "Dependency installation successful."
-        break
-    else
-        echo "Dependency installation failed. Retrying..."
-        sleep 5
-    fi
-done
+if [[ $exit_status -eq 0 ]]; then
+    echo "Dependency installation successful."
+else
+    echo "Dependency installation failed."
+    sleep 5
+fi
